### ISSUE TITLE
【依頼】フリマアプリ挙動確認【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ErikoTakami** [ErikoTakami/furima-28568#11]

**Comment by ErikoTakami** [comment]
# what
フリマアプリの動作確認をお願いします。

# URL
https://furima-28568.herokuapp.com/

# Basic認証のIDとパスワード
ID: mi_taka
パスワード: furima-28568

# 出品者用のメールアドレスとパスワード
email: takami@takami.takami
password: takami0000

# 購入者用のメールアドレスとパスワード
email: yamada@hanako.hanako
password: yamada0000

# 購入用カードの番号・期限・セキュリティコード
number: 4242424242424242
cvc: 123
exp_month: 12
exp_year: 24

**Comment by mo1015** [comment]
高見さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます:tada:
おめでとうございます！

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
